services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      - postgresql
    env_file:
      - ./.env

  postgresql:
    image: docker.io/library/postgres:latest
    ports:
      - 5433:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  postgresql-test:
    image: docker.io/library/postgres:latest
    ports:
      - 5434:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - postgresql

volumes:
  postgres_data:
  postgres_data_test: